#!/bin/bash -ex

dl() {
    [ "$FAB_HTTP_PROXY" ] && PROXY="--proxy $FAB_HTTP_PROXY"
    cd $2; curl -L -f -O $PROXY $1; cd -
}

VERSION="XOOPS%20Core%20%28stable%20releases%29/XOOPS_2.5.8/XoopsCore25-2.5.8.tar.gz"
URL="http://sourceforge.net/projects/xoops/files/$VERSION"

dl $URL /usr/local/src

