#!/bin/bash -ex

dl() {
    [ "$FAB_HTTP_PROXY" ] && PROXY="--proxy $FAB_HTTP_PROXY"
    cd $2; curl -L -f -O $PROXY $1; cd -
}


VERSION="v2.5.10"
URL="https://github.com/XOOPS/XoopsCore25/archive/$VERSION.tar.gz"

dl $URL /usr/local/src

