#!/bin/sh -ex

DB_NAME=xoops
DB_USER=xoops
DB_PREFIX=xoops
DB_PASS=$(mcookie)

ADMIN_NAME=admin
ADMIN_PASS=turnkey
ADMIN_MAIL=admin@example.com

SRC=/usr/local/src
WEBROOT=/var/www/xoops
XOOPS=/var/local/lib/xoops

# unpack and configure
tar -zxf $SRC/xoops-*.tar.gz -C $SRC
cp -a $SRC/xoops-*/htdocs $WEBROOT
cp -TdR $SRC/xoops-*/extras/modules $WEBROOT/modules
rm -rf $SRC/xoops-*
chown -R root:root $WEBROOT
chown -R www-data:www-data $WEBROOT/uploads
chown www-data:www-data $WEBROOT/mainfile.php
chown www-data:www-data $WEBROOT/include/license.php

mkdir -p $XOOPS
mv $WEBROOT/xoops_lib $XOOPS/lib
mv $WEBROOT/xoops_data $XOOPS/data
chown -R www-data:www-data $XOOPS/data/caches
chown -R www-data:www-data $XOOPS/data/data
chown -R www-data:www-data $XOOPS/lib/modules/protector/configs/

# configure apache
a2dissite default
a2ensite xoops
a2enmod rewrite

