#!/bin/bash -e
# regenerate xoops mysql password

. /etc/default/inithooks

CONF=/var/local/lib/xoops/data/data/secure.php

PASSWORD=$(mcookie)
sed -i "s|XOOPS_DB_PASS.*|XOOPS_DB_PASS', '$PASSWORD');|" $CONF
$INITHOOKS_PATH/bin/mysqlconf.py --user=xoops --pass="$PASSWORD"

